# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding Bible
email: moses@caresharing.ph
description: > # this means to ignore newlines until "baseurl:"
  Herewith, contains the rule of law, scriptures, and the good word for us all
  coding mortals in the company.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bible.caresharing" # the base hostname & protocol for your site
twitter_username: codecaresharing
github_username:  caresharing

# Build settings
markdown: kramdown
